exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: Commuting Patterns in the NY-NJ Area
description: Explore the net inflow and outflow of workers and the association between median gross rent and distance to Manhattan
